# please refer xuandb.cluster.toml for documentation

cluster-name = ""

[[node]]
	id = "1"
	http-addr = "127.0.0.1:7001"
	enable-pprof = false

	[node.logger]
		level = "DEBUG"
		format = "text"
		add-source = false
		output-to = "stderr"

	[node.meta]
		raft-voter = true
		raft-addr = "127.0.0.1:8001"
		raft-store = "memory"
		raft-snapshot-store = "memory"
		data-dir = "meta/single"

	[node.data]

	[node.query]
